# Nom de notre workflow
name: "deploy Github pages"

# Événements sur lesquels il doit être déclenché
on:
  push:         # <- Déclenché lorsque l'on pousse du code...
    branches:
      - master  # <- ... mais seulement sur la branche "master"

jobs:

  # Notre job
  build-and-deploy:
    runs-on: ubuntu-latest

    # Tâches à effectuer, comme expliquées ci-dessus
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # Déploiement sur les Github Pages
      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.DOKKA_TOKEN }}
          BRANCH: gh-pages     # <- Branche sur laquelle seront commités les fichiers
          FOLDER: docs  # <- Dossier contenant notre documentation générée
